# Generated by Django 2.1 on 2019-11-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='for_messenger',
            field=models.IntegerField(choices=[(0, 'Telegram'), (1, 'Viber'), (2, 'VK'), (3, 'Facebook'), (4, 'Все')], default=4, verbose_name='Мессенджер'),
        ),
        migrations.AlterField(
            model_name='error',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время'),
        ),
    ]
