# Generated by Django 2.1.7 on 2019-11-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0002_auto_20191119_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOnHelpSerializer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', verbose_name='Ответ')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('category', models.CharField(choices=[('schedule', 'Расписание'), ('bot', 'Бот'), ('other', 'Другое')], max_length=300)),
                ('has_answer', models.BooleanField(default=False, verbose_name='Был ответ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.User', verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='answeronhelpserializer',
            name='help',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.Issue', verbose_name='Претензия пользователя'),
        ),
    ]
