# Generated by Django 2.1.7 on 2019-11-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20191123_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOnHelpSerializer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', verbose_name='Ответ')),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.Help', verbose_name='Претензия пользователя')),
            ],
        ),
    ]
