# Generated by Django 2.1.7 on 2019-11-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20191124_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerOnIssueSerializer',
            new_name='AnswerOnIssue',
        ),
    ]
