# Generated by Django 2.1.7 on 2019-11-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20191124_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeronissue',
            old_name='help',
            new_name='issue',
        ),
    ]
