# Generated by Django 2.1.7 on 2019-11-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_answeronhelpserializer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeronhelpserializer',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='help',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='help',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot.User', verbose_name='Пользователь'),
        ),
    ]
