# Generated by Django 2.1.7 on 2019-11-24 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20191124_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeronissue',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='schedule.Issue', verbose_name='Претензия пользователя'),
        ),
    ]
